// ─────────────────────────────────────────────────────────────────────────────
// agent/demo-responses.ts
//
// Predefined structured responses for the LYNCH AI agent demo.
// Used by ai.ts to simulate intelligent financial analysis without a real model.
//
// ⚠️  All financial figures are fictional and for demo purposes only.
//     LYNCH does not execute real trades or provide financial advice.
// ─────────────────────────────────────────────────────────────────────────────

import {
  DEMO_STOCK_UNIVERSE,
  StockResearchProfile,
} from "./research-data";
import {
  compareStocks,
  analyzeStockInPortfolioContext,
  getSectorResearchSummaries,
  StockComparisonResult,
  PortfolioContextAnalysis,
  SectorResearchSummary,
} from "./analysis-engine";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Directional signal LYNCH assigns to a stock or portfolio. */
export type LynchSignal = "BUY" | "HOLD" | "WATCH" | "REDUCE" | "AVOID";

/** Risk level LYNCH assigns to a response. */
export type LynchRisk = "LOW" | "MODERATE" | "HIGH" | "VERY HIGH";

/** Individual stock idea item generated by SkillPatch idea-generation workflow */
export interface LynchIdea {
  symbol: string;
  name: string;
  signal: LynchSignal;
  confidence: number;
  risk: LynchRisk;
  thesis: string;
  standout: string[];
  risks: string[];
  priority: string;
}

/**
 * The canonical response shape returned by LYNCH.
 * Chat.tsx uses this to render structured cards alongside plain messages.
 */
export interface LynchResponse {
  /** Unique identifier for the intent this response addresses. */
  intent: string;

  /** The main prose message from LYNCH. Always present. */
  message: string;

  /**
   * Optional rich equity research profile.
   * Present for stock analysis responses.
   */
  stockProfile?: StockResearchProfile;

  /**
   * Optional stock comparison data structure.
   */
  comparison?: StockComparisonResult;

  /**
   * Optional portfolio context analysis.
   */
  portfolioContext?: PortfolioContextAnalysis;

  /**
   * Optional sector research block.
   */
  sectorSummaries?: SectorResearchSummary[];

  /**
   * Optional structured analysis block (backwards compatibility & portfolio summaries).
   */
  analysis?: {
    /** Ticker or entity being analysed (e.g. "RELIANCE", "Portfolio"). */
    subject: string;
    /** Demo price / value in local currency (string for display flexibility). */
    price?: string;
    /** 1-day change percentage, e.g. "+1.4%" */
    change?: string;
    /** Directional signal. */
    signal: LynchSignal;
    /** 0–100 confidence score. */
    confidence: number;
    /** Risk classification. */
    risk: LynchRisk;
    /** Short bullet-point reasons backing the signal. */
    reasons: string[];
    /** Actionable next steps the user might consider. */
    suggestedActions: string[];
  };

  /**
   * Optional investment ideas block.
   * Uses SkillPatch vs-equity-research-idea-generation workflow.
   */
  ideasBlock?: {
    methodology: string;
    count: number;
    ideas: LynchIdea[];
    priorities: Array<{ symbol: string; priorityLabel: string }>;
    disclaimer: string;
  };

  /** Optional follow-up prompt suggestions shown in the chat UI. */
  followUps?: string[];
}

// ---------------------------------------------------------------------------
// Demo responses keyed by intent string
// ---------------------------------------------------------------------------

const RESPONSES: Record<string, LynchResponse> = {
  // ─── 0. Greeting ──────────────────────────────────────────────────────────
  greeting: {
    intent: "greeting",
    message:
      "Hello! I'm LYNCH, your AI investment co-pilot. I can help you analyze stocks, review your portfolio, understand risk alerts, and explore investment ideas using demo market data. What would you like to explore today?",
    followUps: [
      "What stocks look interesting?",
      "Show my portfolio",
      "What is LYNCH?",
    ],
  },

  // ─── 1. Reliance Industries ──────────────────────────────────────────────
  reliance: {
    intent: "reliance",
    message:
      "Based on LYNCH's pattern analysis of RELIANCE, the stock shows renewed momentum after consolidating near its 52-week support band. Institutional accumulation signals are above average this week.",
    analysis: {
      subject: "RELIANCE",
      price: "₹2,847.60",
      change: "+1.4%",
      signal: "BUY",
      confidence: 74,
      risk: "MODERATE",
      reasons: [
        "3-day consecutive close above 200-DMA (₹2,801)",
        "RSI recovering from oversold zone — now at 54",
        "Jio segment revenue beat consensus by ~6% last quarter",
        "Futures open interest up 18% — bullish positioning",
        "Retail + green energy capex cycle entering execution phase",
      ],
      suggestedActions: [
        "Consider initiating a starter position near current levels",
        "Set a stop-loss below ₹2,780 to manage downside",
        "Watch the ₹2,950 zone as the first meaningful resistance",
        "Avoid over-sizing — sector rotation risk remains",
      ],
    },
    followUps: [
      "What is the risk on Reliance?",
      "Compare Reliance vs TCS",
      "Show my portfolio",
    ],
  },

  // ─── 2. TCS ─────────────────────────────────────────────────────────────
  tcs: {
    intent: "tcs",
    message:
      "LYNCH's read on TCS is cautiously optimistic. The stock trades at a premium valuation, and near-term upside may be limited until the next earnings catalyst. Ideal for existing holders, not a rush-entry.",
    analysis: {
      subject: "TCS",
      price: "₹3,912.00",
      change: "-0.3%",
      signal: "HOLD",
      confidence: 68,
      risk: "LOW",
      reasons: [
        "P/E at 28x — fair but not cheap for current growth rate",
        "Deal wins pipeline healthy; TCV guidance maintained",
        "Margin pressure from wage hikes persists into Q2",
        "USD/INR tailwind providing partial buffer on revenue",
        "Dividend yield of 1.8% provides floor support",
      ],
      suggestedActions: [
        "Hold existing position — fundamentals remain intact",
        "Avoid adding aggressively before next earnings (3 weeks)",
        "Use any 3–4% dip as an accumulation opportunity",
        "Pair with a growth-oriented IT mid-cap for balance",
      ],
    },
    followUps: [
      "How does TCS compare to Infosys?",
      "What is my IT sector exposure?",
      "What should I watch?",
    ],
  },

  // ─── 3. Infosys ─────────────────────────────────────────────────────────
  infy: {
    intent: "infy",
    message:
      "LYNCH flags INFY as a near-term watch candidate. The stock broke a key trendline yesterday and volume spiked 2.3x average. This pattern often precedes a decisive move — direction is still being confirmed.",
    analysis: {
      subject: "INFY",
      price: "₹1,743.50",
      change: "+2.1%",
      signal: "WATCH",
      confidence: 58,
      risk: "MODERATE",
      reasons: [
        "Trendline break with elevated volume — pattern in progress",
        "Management guided FY26 revenue growth at 4–7% (midpoint raised)",
        "Cloud & AI services segment growing at 31% YoY",
        "FII net buying for 4 consecutive sessions",
        "Uncertainty on large deal ramp-ups dampens near-term visibility",
      ],
      suggestedActions: [
        "Watch for a confirmed close above ₹1,760 before entering",
        "Set an alert at ₹1,760 — LYNCH will notify you on breach",
        "Avoid entering ahead of the pending US client spend data",
        "Risk-reward improves significantly above breakout confirmation",
      ],
    },
    followUps: [
      "Set an alert for INFY at ₹1,760",
      "Compare INFY vs TCS",
      "Analyse my portfolio risk",
    ],
  },

  // ─── 4. HDFC Bank ───────────────────────────────────────────────────────
  hdfcbank: {
    intent: "hdfcbank",
    message:
      "HDFCBANK is recovering from its post-merger integration overhang. LYNCH sees this as a multi-quarter accumulation opportunity for patient investors. Short-term traders should note that the stock has underperformed Nifty Bank by ~9% YTD.",
    analysis: {
      subject: "HDFCBANK",
      price: "₹1,621.80",
      change: "+0.7%",
      signal: "BUY",
      confidence: 71,
      risk: "LOW",
      reasons: [
        "NIM stabilising at 3.5% — worst appears priced in",
        "CD ratio normalising after elevated post-merger period",
        "CASA ratio improved to 42.1% from 40.3% last quarter",
        "FII holdings at 3-year low — mean reversion potential",
        "Stock at 1.9x book — historically a strong entry band",
      ],
      suggestedActions: [
        "Suitable for a core long-term holding (12–18 month horizon)",
        "Systematic accumulation preferred over lump-sum entry",
        "Stop consideration: ₹1,570 (structural support zone)",
        "Catalyst to watch: RBI rate cut cycle pace in Q3",
      ],
    },
    followUps: [
      "What is my banking sector exposure?",
      "Compare HDFCBANK vs ICICIBANK",
      "Analyse my portfolio risk",
    ],
  },

  // ─── 5. NVIDIA ──────────────────────────────────────────────────────────
  nvda: {
    intent: "nvda",
    message:
      "NVDA remains LYNCH's highest-conviction global pick, but the valuation demands respect. At these levels, the stock prices in flawless execution for the next 6 quarters. Any guide-down on Blackwell shipments could trigger a sharp correction.",
    analysis: {
      subject: "NVDA",
      price: "$134.20",
      change: "+3.2%",
      signal: "HOLD",
      confidence: 65,
      risk: "HIGH",
      reasons: [
        "Data center revenue up 427% YoY — demand remains insatiable",
        "Blackwell GPU ramp ahead of schedule per supply chain checks",
        "Forward P/E of 42x bakes in near-perfect growth continuation",
        "Export restriction risk to China (~15% revenue exposure)",
        "AMD & Intel mounting credible Datacenter AI competition",
      ],
      suggestedActions: [
        "Trim 10–15% if you're above target weight in the position",
        "Avoid new aggressive entries at ATH without a pullback",
        "Set a trailing stop at $118 to protect gains",
        "Earnings in ~6 weeks — consider holding through the event",
      ],
    },
    followUps: [
      "What is my US tech exposure?",
      "Compare NVDA vs AMD",
      "What should I watch this week?",
    ],
  },

  // ─── 6. Portfolio Analysis ───────────────────────────────────────────────
  portfolio_analysis: {
    intent: "portfolio_analysis",
    message:
      "Your demo portfolio is moderately well-diversified but has a noticeable tilt toward large-cap IT. LYNCH identifies one underweight area (financials) and one over-concentration (tech at 38% of equity).",
    analysis: {
      subject: "Portfolio",
      price: "₹12,48,350",
      change: "+0.9% today",
      signal: "HOLD",
      confidence: 72,
      risk: "MODERATE",
      reasons: [
        "IT/Tech at 38% — above the 25% benchmark weight",
        "Financials at 11% — significantly underweight vs 22% benchmark",
        "Top 3 holdings account for 54% of total equity",
        "No international diversification in current allocation",
        "Gold allocation (7%) provides inflation buffer — appropriate",
      ],
      suggestedActions: [
        "Consider trimming IT exposure by 8–10% on the next rally",
        "Redeploy into banking — HDFCBANK or ICICIBANK look interesting",
        "Add a US index ETF for geographic diversification",
        "Review the portfolio again after next week's inflation print",
      ],
    },
    followUps: [
      "What is my portfolio risk?",
      "Analyse HDFCBANK",
      "What should I watch?",
    ],
  },

  // ─── 7. Portfolio Risk ───────────────────────────────────────────────────
  portfolio_risk: {
    intent: "portfolio_risk",
    message:
      "LYNCH's risk scan shows your portfolio has moderate overall risk, but with elevated concentration risk in IT. A sector-level correction in tech of 15% would impact your portfolio by approximately ₹71,000.",
    analysis: {
      subject: "Portfolio Risk",
      signal: "WATCH",
      confidence: 78,
      risk: "MODERATE",
      reasons: [
        "Concentration risk: IT at 38% (threshold: 25%)",
        "Beta of 1.14 vs Nifty 50 — above-average market sensitivity",
        "3 positions with individual weight > 15% each",
        "Low sector correlation between holdings — partially offsetting",
        "No active hedge (puts / inverse ETF) in the current book",
      ],
      suggestedActions: [
        "Set position-size alerts for any holding that crosses 20%",
        "Consider a small Nifty put spread ahead of next RBI policy",
        "Rebalancing every quarter reduces drift risk meaningfully",
        "Max drawdown tolerance: review if Nifty corrects > 8%",
      ],
    },
    followUps: [
      "Show my full portfolio",
      "Analyse HDFCBANK",
      "What should I watch this week?",
    ],
  },

  // ─── 8. Watchlist Suggestions ────────────────────────────────────────────
  watchlist: {
    intent: "watchlist",
    message:
      "Based on current market patterns and your portfolio gaps, LYNCH has shortlisted 4 names worth monitoring this week. These are not buy signals — they are stocks where something interesting is developing.",
    analysis: {
      subject: "Watchlist",
      signal: "WATCH",
      confidence: 66,
      risk: "MODERATE",
      reasons: [
        "INFY — trendline break in progress, awaiting confirmation",
        "HDFCBANK — CD ratio normalising; FII accumulation starting",
        "LTIM — midcap IT with strong deal wins, less stretched valuation",
        "TATASTEEL — commodity cycle turn; breakout from 6-month base",
      ],
      suggestedActions: [
        "Add INFY and HDFCBANK to your alert list at key levels",
        "Review LTIM earnings (due in 9 days) before entering",
        "TATASTEEL is higher-risk — size accordingly if interested",
        "Revisit this list after Thursday's macro data releases",
      ],
    },
    followUps: [
      "Analyse INFY",
      "Analyse HDFCBANK",
      "Set an alert for INFY",
    ],
  },

  // ─── 9. Alert Explanation ────────────────────────────────────────────────
  alert_explanation: {
    intent: "alert_explanation",
    message:
      "LYNCH triggered an alert on INFY at ₹1,743 because the stock closed above a descending trendline that had held for 47 days, with volume 2.3× its 20-day average. This is a pattern LYNCH monitors as a potential breakout signal.",
    analysis: {
      subject: "INFY Alert",
      price: "₹1,743.50",
      change: "+2.1%",
      signal: "WATCH",
      confidence: 61,
      risk: "MODERATE",
      reasons: [
        "47-day descending trendline broken on high volume",
        "Volume at 2.3× the 20-day average — institutional involvement",
        "RSI crossed 55 — first time in 7 weeks",
        "Pattern matches 3 prior breakout setups in INFY (2022–2024)",
        "Not yet confirmed — one more close above ₹1,750 strengthens the case",
      ],
      suggestedActions: [
        "Watch for a second close above ₹1,750 for confirmation",
        "Don't act on the alert alone — wait for follow-through",
        "LYNCH will update you if volume sustains tomorrow",
        "This alert does not constitute a trade recommendation",
      ],
    },
    followUps: [
      "Analyse INFY in detail",
      "Set an alert for INFY at ₹1,760",
      "What else should I watch?",
    ],
  },

  // ─── 10. What is LYNCH? ──────────────────────────────────────────────────
  what_is_lynch: {
    intent: "what_is_lynch",
    message:
      "LYNCH is an AI-powered investment research assistant prototype — named after legendary investor Peter Lynch. It analyzes demo stock data, provides portfolio insights, generates investment ideas, and helps you understand market patterns.\n\n⚠️ DISCLAIMER: This prototype uses DEMO DATA ONLY and does not provide real-time financial advice or execute live trades.",
    followUps: [
      "Show my portfolio",
      "What stocks look interesting?",
      "Analyse RELIANCE",
    ],
  },

  // ─── 11. General Risks ───────────────────────────────────────────────────
  general_risks: {
    intent: "general_risks",
    message:
      "Every equity investment carries distinct risk factors. Across our demo portfolio, LYNCH identifies four primary risk vectors:\n\n1. Concentration Risk: Tech sector over-exposure (38% of portfolio vs 25% benchmark).\n2. Volatility Risk: Market beta of 1.14 on key holdings.\n3. Valuation Risk: Premium P/E multiples on high-growth IT names.\n4. Macro & Rate Sensitivity: Potential earnings impact from global enterprise spend shifts.\n\n⚠️ Note: All metrics are derived from demo data for hackathon testing.",
    analysis: {
      subject: "General Risk Overview",
      signal: "WATCH",
      confidence: 76,
      risk: "MODERATE",
      reasons: [
        "Sector concentration: IT sector accounts for 38% of total portfolio value",
        "Beta sensitivity: 1.14x vs broad market index",
        "Macro risks: Interest rate volatility & global tech spending slowdowns",
        "Single-stock weight: Top 3 holdings comprise >50% of portfolio value",
      ],
      suggestedActions: [
        "Review single-stock position sizing to cap max weight at 15%",
        "Rebalance into defensive/financial sectors (e.g. HDFCBANK)",
        "Use stop-loss levels on high-beta equity positions",
      ],
    },
    followUps: [
      "What is my portfolio risk?",
      "Tell me about TCS",
      "What stocks look interesting?",
    ],
  },

  // ─── 12. Investment Ideas (vs-equity-research-idea-generation) ───────────
  investment_ideas: {
    intent: "investment_ideas",
    message:
      "LYNCH INVESTMENT IDEAS\n\nBased on the current demo dataset and quantitative screening criteria (Value, Quality & Growth), I found 3 ideas worth researching. (Demonstrating SkillPatch vs-equity-research-idea-generation methodology)",
    ideasBlock: {
      methodology:
        "Applied SkillPatch idea-generation workflow: Search Criteria (Large/Mid Cap Quality & Value) → Quantitative Screen (P/E, ROE, FCF Yield) → Thematic Sweep (AI Services, Retail Execution, Credit Normalization)",
      count: 3,
      ideas: [
        {
          symbol: "TCS",
          name: "Tata Consultancy Services",
          signal: "BUY",
          confidence: 82,
          risk: "LOW",
          thesis:
            "Strong deal-win pipeline and steady digital transformation capex give TCS high revenue visibility. Fair valuation with strong cash flow conversion.",
          standout: [
            "Positive momentum with steady margin resilience",
            "High return on equity (>35%) and zero debt balance sheet",
            "Attractive deal-win TCV pipeline in Cloud & AI services",
          ],
          risks: [
            "Near-term wage inflation pressures",
            "Global IT spend slowdown risk",
          ],
          priority: "Highest priority",
        },
        {
          symbol: "RELIANCE",
          name: "Reliance Industries Ltd",
          signal: "HOLD",
          confidence: 78,
          risk: "MODERATE",
          thesis:
            "Jio telecom revenue momentum and retail expansion cushion capex cycles. Consolidation above 200-DMA signals strong institutional support.",
          standout: [
            "Positive momentum & institutional accumulation signal",
            "Strong quality metrics across telecom and retail verticals",
            "Attractive demo valuation signal near major support band",
          ],
          risks: [
            "Elevated volatility due to green energy capex cycle",
            "Valuation overhang from multi-sector execution",
          ],
          priority: "Medium priority",
        },
        {
          symbol: "INFY",
          name: "Infosys Ltd",
          signal: "WATCH",
          confidence: 71,
          risk: "MODERATE",
          thesis:
            "Breakout pattern on high volume with accelerating growth in Cloud & AI services (31% YoY). Awaiting second close confirmation.",
          standout: [
            "Volume spike (2.3x average) on technical trendline break",
            "Raised FY26 growth guidance with expanding margins",
            "Strong net foreign institutional buying over last 4 sessions",
          ],
          risks: [
            "Sensitivity to US enterprise tech spending budgets",
            "Volatile deal ramp-up timelines",
          ],
          priority: "Watch list candidate",
        },
      ],
      priorities: [
        { symbol: "TCS", priorityLabel: "Highest priority" },
        { symbol: "RELIANCE", priorityLabel: "Medium priority" },
        { symbol: "INFY", priorityLabel: "Watch" },
      ],
      disclaimer:
        "DEMO DATA ONLY — Screened using local project demo metrics. Not real-time financial advice.",
    },
    followUps: [
      "Analyse TCS in detail",
      "Compare RELIANCE vs INFY",
      "Show my portfolio risk",
    ],
  },

  // ─── 13. Out of Scope ────────────────────────────────────────────────────
  out_of_scope: {
    intent: "out_of_scope",
    message:
      "I'm currently focused on investment research, portfolio insights, stock analysis, alerts, and investment ideas using our demo dataset. Try asking me about a stock like TCS or RELIANCE, or ask to view your demo portfolio!",
    followUps: [
      "Show my portfolio",
      "What stocks look interesting?",
      "Analyse TCS",
    ],
  },

  // ─── 14. Generic Fallback ────────────────────────────────────────────────
  fallback: {
    intent: "fallback",
    message:
      "I'm focused on investment research, portfolio insights, stock analysis, alerts, and investment ideas. Try asking me about a stock, reviewing your demo portfolio, or finding new stock opportunities!",
    followUps: [
      "Analyse RELIANCE",
      "Show my portfolio",
      "What stocks look interesting?",
      "What is LYNCH?",
    ],
  },
};

// ---------------------------------------------------------------------------
// Public lookup function
// ---------------------------------------------------------------------------

/**
 * Returns the structured LYNCH response for a given intent key or dynamic query.
 * Falls back to the generic fallback response if the intent is unknown.
 */
export function getDemoResponse(intent: string): LynchResponse {
  // Handle stock-specific profiles dynamically
  const upperIntent = intent.toUpperCase();
  if (DEMO_STOCK_UNIVERSE[upperIntent]) {
    const stock = DEMO_STOCK_UNIVERSE[upperIntent];
    return {
      intent: intent.toLowerCase(),
      message: `Here is the comprehensive LYNCH Equity Research brief for ${stock.companyName} (${stock.symbol}).`,
      stockProfile: stock,
      analysis: {
        subject: stock.symbol,
        price: stock.price,
        change: stock.change,
        signal: stock.signal as LynchSignal,
        confidence: stock.confidence,
        risk: stock.riskLevel as LynchRisk,
        reasons: [
          `Research Score: ${stock.researchScore}/100 (${stock.researchPriority})`,
          `ROE: ${stock.fundamentals.roe}% | Operating Margin: ${stock.fundamentals.operatingMargin}`,
          `Valuation: ${stock.valuation.pe}x P/E (${stock.valuation.assessment})`,
          stock.lynchTakeaway,
        ],
        suggestedActions: [
          `Review ${stock.symbol} catalysts and risk factors`,
          `Ask "How does ${stock.symbol} affect my portfolio?"`,
          `Compare ${stock.symbol} with industry peers`,
        ],
      },
      followUps: [
        `How does ${stock.symbol} affect my portfolio?`,
        `What are the key risks of ${stock.symbol}?`,
        `Compare ${stock.symbol} and INFY`,
      ],
    };
  }

  // Handle comparison requests
  if (intent.startsWith("compare_")) {
    const parts = intent.replace("compare_", "").split("_vs_");
    if (parts.length === 2) {
      const comp = compareStocks(parts[0], parts[1]);
      if (comp) {
        return {
          intent,
          message: `LYNCH Stock Comparison: ${comp.stockA.symbol} vs ${comp.stockB.symbol}. ${comp.verdict}`,
          comparison: comp,
          followUps: [
            `Analyse ${comp.stockA.symbol}`,
            `Analyse ${comp.stockB.symbol}`,
            `Show me investment ideas`,
          ],
        };
      }
    }
  }

  // Handle portfolio context queries
  if (intent.startsWith("portfolio_context_")) {
    const symbol = intent.replace("portfolio_context_", "").toUpperCase();
    const portCtx = analyzeStockInPortfolioContext(symbol);
    if (portCtx) {
      return {
        intent,
        message: `LYNCH Portfolio Integration Analysis for ${portCtx.stock.symbol}: ${portCtx.portfolioRiskImpact}`,
        portfolioContext: portCtx,
        stockProfile: portCtx.stock,
        followUps: [
          `Analyse ${portCtx.stock.symbol}`,
          `How risky is my portfolio?`,
          `Give me investment ideas`,
        ],
      };
    }
  }

  // Handle sector research queries
  if (intent === "sector_research") {
    const summaries = getSectorResearchSummaries();
    return {
      intent: "sector_research",
      message: "Here is the LYNCH Sector Intelligence breakdown across primary domestic sectors in our demo research universe.",
      sectorSummaries: summaries,
      followUps: [
        "Analyse TCS",
        "Analyse ICICIBANK",
        "Analyse RELIANCE",
      ],
    };
  }

  return RESPONSES[intent] ?? RESPONSES["fallback"];
}

/**
 * Returns all available intent keys.
 * Useful for ai.ts to enumerate supported intents.
 */
export function getAvailableIntents(): string[] {
  return Object.keys(RESPONSES);
}
